/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gianniBadge2.glb --transform 
Files: gianniBadge2.glb [4.74MB] > C:\Users\giann\OneDrive\Documenti\3DPortfolio\g-portfolio\public\gianniBadge2-transformed.glb [73.94KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gianniBadge2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.card.geometry} material={materials['base.005']} />
      <mesh geometry={nodes.clip.geometry} material={materials['metal.005']} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.003']} position={[-0.301, 0.217, 0.04]} rotation={[1.654, -0.001, 0.006]} scale={0.123} />
      <mesh geometry={nodes.IMG_20240706_195900433_MF_PORTRAITTagliataNoSfondo.geometry} material={materials.IMG_20240706_195900433_MF_PORTRAITTagliataNoSfondo} position={[-0.005, 0.652, 0.044]} rotation={[1.537, 0.005, -0.025]} scale={0.644} />
    </group>
  )
}

useGLTF.preload('/gianniBadge2-transformed.glb')
