/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 gianniBadgeV0-amber-v1.glb --transform 
Files: gianniBadgeV0-amber-v1.glb [560.34KB] > C:\Users\giann\OneDrive\Documenti\3DPortfolio\g-portfolio\public\gianniBadgeV0-amber-v1-transformed.glb [84.74KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gianniBadgeV0-amber-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.card.geometry} material={materials['base.005']} />
      <mesh geometry={nodes.clip.geometry} material={materials['metal.005']} />
      <mesh geometry={nodes['gianni-blur'].geometry} material={materials['gianni-blur']} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/gianniBadgeV0-amber-v1-transformed.glb')
